// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-ui/lib/button')['default']
    ElDialog: typeof import('element-ui/lib/dialog')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElMenuItemGroup: typeof import('element-ui/lib/menu-item-group')['default']
    ElOption: typeof import('element-ui/lib/option')['default']
    ElSelect: typeof import('element-ui/lib/select')['default']
    ElSkeleton: typeof import('element-ui/lib/skeleton')['default']
    ElSkeletonItem: typeof import('element-ui/lib/skeleton-item')['default']
    ElSubmenu: typeof import('element-ui/lib/submenu')['default']
    ElTable: typeof import('element-ui/lib/table')['default']
    ElTableColumn: typeof import('element-ui/lib/table-column')['default']
    ElTag: typeof import('element-ui/lib/tag')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
