server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"


database:
  host: 127.0.0.1
  port: 5432
  dbname: monitor
  user: postgres
  password: bgy123456

# Redis 配置示例
redis:
  # 单实例配置示例1
  default:
    address: 140.238.26.86:6379
    db:          1
    pass: dalong
    idleTimeout: 600


logger:
  level : "all"
  stdout: true
  stdoutColorDisabled: true

gfcli:
  build:
    name:     "gf"
    arch:     "all"
    system:   "all"
    mod:      "none"
    packSrc:  "resource,manifest"
    version:  "v1.0.0"
    output:   "./bin"
    extra:    ""
