user-agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

cron: "*/5 * * * *"


database:
  host: 127.0.0.1
  port: 5432
  dbname: monitor
  user: postgres
  password: bgy123456
