server:
  address:     "0.0.0.0:8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"


database:
  host: 127.0.0.1
  port: 5432
  dbname: monitor
  user: postgres
  password: bgy123456

# Redis 配置示例
redis:
  # 单实例配置示例1
  default:
    address: 127.0.0.1:6379
    db:          8
    idleTimeout: 600


logger:
  level : "all"
  stdout: true
  stdoutColorDisabled: true

# 登录token信息加密字符串，必须修改！！！！！！！！！！！！！
jwt:
  secret: "oiewhfoirtgbisaugqwe"
